-- ============================================
-- 1. جدول الوجبات (Products)
-- ============================================
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  category TEXT NOT NULL,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- 2. جدول الطلبات (Orders) - كان ناقصاً تماماً!
-- ============================================
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_address TEXT NOT NULL,
  notes TEXT,
  total_price NUMERIC NOT NULL DEFAULT 0,
  items JSONB DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'جديد',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- 3. تفعيل صلاحيات الوصول (RLS Policies)
-- ============================================
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read on products"
  ON public.products FOR SELECT USING (true);

CREATE POLICY "Allow public insert/update/delete on products"
  ON public.products FOR ALL USING (true);

CREATE POLICY "Allow public read/insert on orders"
  ON public.orders FOR SELECT USING (true);

CREATE POLICY "Allow public insert on orders"
  ON public.orders FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update/delete on orders"
  ON public.orders FOR ALL USING (true);